E3DBPI/Models/BlogPost.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BlogPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogPost()
        {
            this.BlogComments = new HashSet<BlogComment>();
        }
    
        public int PostID { get; set; }
        public int Post_CategoryID { get; set; }
        public string Post_author { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime Post_Date { get; set; }
        public string Post_Tite { get; set; }
        public string Post_Content { get; set; }
        public string Post_Status { get; set; }
        public bool Post_Deleted { get; set; }
        public bool Post_Active { get; set; }
        public bool Post_Featured { get; set; }
        public Nullable<int> Post_Views { get; set; }
        public bool Post_CommentsAllowed { get; set; }
        public string Post_Image1 { get; set; }
        public string Post_Image2 { get; set; }
        public string Post_Image3 { get; set; }
        public string Post_Banner1 { get; set; }
        public string Post_Article { get; set; }
        public string Post_ArticleContent { get; set; }
        public string Post_URL1 { get; set; }
        public string Post_URL2 { get; set; }
        public bool Post_CommentsReview { get; set; }
    
        public virtual BlogCategory BlogCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogComment> BlogComments { get; set; }
    }
}

E3DBPI/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E3DBPI.Models;

namespace E3DBPI.Controllers
{

    public class BlogPostsController : Controller
    {
        private SiteDBEntities db = new SiteDBEntities();

        // GET: BlogPosts
        [Authorize(Roles = "SuperAdmin, Author")]
        public ActionResult Index()
        {
            var blogPosts = db.BlogPosts.Include(b => b.BlogCategory);
            return View(blogPosts.ToList());
        }
        // GET: BlogPosts
        public ActionResult NewsnEvents()
        {
            var blogPosts = db.BlogPosts.Include(b => b.BlogCategory);
            return View(blogPosts.ToList());
        }


        // GET: BlogPosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "SuperAdmin, Author")]
        public ActionResult Create()
        {
            ViewBag.Post_CategoryID = new SelectList(db.BlogCategories, "Post_CategoryID", "Post_CategoryName");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PostID,Post_CategoryID,Post_author,Post_Date,Post_Tite,Post_Content,Post_Status,Post_Deleted,Post_Active,Post_Featured,Post_Views,Post_CommentsAllowed,Post_Image1,Post_Image2,Post_Image3,Post_Banner1,Post_Article,Post_ArticleContent,Post_URL1,Post_URL2,Post_CommentsReview")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Post_CategoryID = new SelectList(db.BlogCategories, "Post_CategoryID", "Post_CategoryName", blogPost.Post_CategoryID);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "SuperAdmin, Author")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            ViewBag.Post_CategoryID = new SelectList(db.BlogCategories, "Post_CategoryID", "Post_CategoryName", blogPost.Post_CategoryID);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PostID,Post_CategoryID,Post_author,Post_Date,Post_Tite,Post_Content,Post_Status,Post_Deleted,Post_Active,Post_Featured,Post_Views,Post_CommentsAllowed,Post_Image1,Post_Image2,Post_Image3,Post_Banner1,Post_Article,Post_ArticleContent,Post_URL1,Post_URL2,Post_CommentsReview")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Post_CategoryID = new SelectList(db.BlogCategories, "Post_CategoryID", "Post_CategoryName", blogPost.Post_CategoryID);
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "SuperAdmin, Author")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

E3DBPI/Views/BlogPosts/Delete.cshtml
@model E3DBPI.Models.BlogPost

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post_author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Tite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Tite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Featured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Featured)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Views)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_CommentsAllowed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_CommentsAllowed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Image1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Image1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Image2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Image2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Image3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Image3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Banner1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Banner1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Article)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_Article)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_ArticleContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_ArticleContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_URL1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_URL1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_URL2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_URL2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_CommentsReview)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post_CommentsReview)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogCategory.Post_CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogCategory.Post_CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

E3DBPI/Views/BlogPosts/Details.cshtml
@model E3DBPI.Models.BlogPost

@{
    ViewBag.Title = "Contraxtor Article";
}
<section class="container" id="articlepost" style="text-align:center">
    <article>
        <div style="text-align:center; margin-top:15px;">
            <h2>@Html.DisplayFor(model => model.Post_Tite)</h2>
            <hr />
            <img src="/images/@Html.DisplayFor(model => model.Post_Image1)" style="max-width:640px;">

            <div class="row">
                <div class="col-md-4 text-right">
                    <p>Author: @Html.DisplayFor(model => model.Post_author)</p>
                </div>
                <div class="col-md-4">
                    <p>Category: @Html.DisplayFor(model => model.Post_CategoryID)</p>
                </div>
                <div class="col-md-4 text-left">
                    <p>@Html.DisplayFor(model => model.Post_Date)</p>
                </div>
            </div>
            <h3 style="font-style:italic;margin-left:0;margin-right:0;"> @Html.DisplayFor(model => model.Post_Content)</h3>
        </div>
        <div class="row" style="margin-top:40px;margin-bottom:40px;">
            <div class="col-md-12">
                <p style="font-size:16px;"> @Html.DisplayFor(model => model.Post_ArticleContent)</p>
            </div>
        </div>

            <!-- Social Media SHARE buttons -->
            <h4 style="text-align:left">Share this Article on:</h4>
            <div class="row center-block" style="margin-bottom:20px; float:none; text-align:left">
                <div style="float:left; margin-right:10px;"> <a href="https://www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark"></a>
                </div>

                <div style="float:left;margin-right:10px;" class="fb-share-button" data-href='/BlogPosts/Details?ID=@Html.DisplayFor(model => model.PostID)' data-layout="button"> </div>

                <div style="float:left;margin-right:10px;">
                    <a class="twitter-share-button" href="https://twitter.com/intent/tweet?"></a>
                    <link rel="canonical" href='/BlogPosts/Details?ID=@Html.DisplayFor(model => model.PostID)' />
                </div>

                <div style="float:left;margin-right:10px;" class="g-plus" data-action="share" data-annotation="none" data-href='/BlogPosts/Details?ID=@Html.DisplayFor(model => model.PostID)'></div>

                <div style="float:left;margin-right:10px;">
                <script type="IN/Share">
                </script>
                </div>
            </div>
        </article>

    <div class="row buttonbox">
        <div class="col-md-4">
            @Html.ActionLink("Previous Article", "Details", "BlogPosts", new { id = Model.PostID }, htmlAttributes: new { @class = "btn btn-lg btn-primary" })
        </div>
        <div class="col-md-4">
            @*@Html.ActionLink("Back to News & Events", "NewsnEvents", "BlogPosts", new { }, htmlAttributes: new { @class = "btn btn-lg btn-primary" })*@
            <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-lg btn-primary" role="button" aria-disabled="true">Return</a>
        </div>
        <div class="col-md-4">
            @Html.ActionLink("Next Article", "Details", "BlogPosts", new { id = Model.PostID }, htmlAttributes: new { @class = "btn btn-lg btn-primary" })
        </div>
    </div>

        @if (User.Identity.IsAuthenticated)
        {
            if (User.IsInRole("SuperAdmin"))
            {

                <h3 style="margin-top:60px; margin-bottom:20px;">Administrator Section</h3>
                <div>
                    @Html.ActionLink("Manage Article Comments", "Index", "BlogComments", new { id = Model.PostID }, htmlAttributes: new { @class = "btn btn-lg btn-warning" })
                    @Html.ActionLink("Create a New Article", "Create", "BlogPosts", new { }, htmlAttributes: new { @class = "btn btn-lg btn-primary" })
                    @Html.ActionLink("Edit this Article", "Edit", new { id = Model.PostID }, htmlAttributes: new { @class = "btn btn-lg btn-success" })
                    @Html.ActionLink("Delete this Article", "Delete", new { id = Model.PostID }, htmlAttributes: new { @class = "btn btn-lg btn-danger" })
                </div>
                <div class="row" style="margin-top:20px;">
                    <div class="col-md-2">
                        Category: @Html.DisplayFor(model => model.BlogCategory.Post_CategoryName)
                    </div>
                    <div class="col-md-2">
                        Comments Allowed: @Html.DisplayFor(model => model.Post_CommentsAllowed)
                    </div>
                    <div class="col-md-2">
                        Review Comments: @Html.DisplayFor(model => model.Post_CommentsReview)
                    </div>
                    <div class="col-md-2">
                        Post Status: @Html.DisplayFor(model => model.Post_Status)
                    </div>
                    <div class="col-md-2">
                        Featured: @Html.DisplayFor(model => model.Post_Featured)
                    </div>
                    <div class="col-md-2">
                        Views: @Html.DisplayFor(model => model.Post_Views)
                    </div>
                </div>
                <div class="row" style="margin-top:20px;">
                    <div class="col-md-3">
                        Image 1: @Html.DisplayFor(model => model.Post_Image1)<br />
                        <img src="/images/@Html.DisplayFor(model => model.Post_Image1)" style="max-width:240px;">
                    </div>
                    <div class="col-md-3">
                        Image 2: @Html.DisplayFor(model => model.Post_Image1)<br />
                        <img src="/images/@Html.DisplayFor(model => model.Post_Image2)" alt="No Image" style="max-width:240px;">
                    </div>
                    <div class="col-md-3">
                        Image 3: @Html.DisplayFor(model => model.Post_Image1)<br />
                        <img src="/images/@Html.DisplayFor(model => model.Post_Image3)" alt="No Image" style="max-width:240px;">
                    </div>
                    <div class="col-md-3">
                        Banner 1: @Html.DisplayFor(model => model.Post_Banner1)<br />
                        <img src="/images/@Html.DisplayFor(model => model.Post_Banner1)" alt="No Image" style="max-width:240px;">
                    </div>
                </div>
                <div class="row" style="margin-top:20px;">
                    <div class="col-md-3">
                        Link1 URL: @Html.DisplayFor(model => model.Post_URL1)
                    </div>
                    <div class="col-md-3">
                        Link2 URL: @Html.DisplayFor(model => model.Post_URL2)
                    </div>
                    <div class="col-md-3">

                    </div>
                    <div class="col-md-3">

                    </div>
                </div>
                <div class="row" style="margin-top:20px;">
                    <div class="col-md-3">
                        Active: @Html.DisplayFor(model => model.Post_Active)
                    </div>
                    <div class="col-md-3">
                        Deleted: @Html.DisplayFor(model => model.Post_Deleted)
                    </div>
                    <div class="col-md-3">
                    </div>
                    <div class="col-md-3">

                    </div>
                </div>
            }
        }

</section>
<script src="//platform.linkedin.com/in.js" type="text/javascript"> lang: en_US</script>

<script type="text/javascript">

    window.twttr = (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
            t = window.twttr || {};
        if (d.getElementById(id)) return t;
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);

        t._e = [];
        t.ready = function (f) {
            t._e.push(f);
        };

        return t;
    }(document, "script", "twitter-wjs"));


    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<script type="text/javascript"
        async defer
        src="//assets.pinterest.com/js/pinit.js">
</script>

<script type="text/javascript" src="https://apis.google.com/js/platform.js" async defer></script>
<script src="https://apis.google.com/js/platform.js"></script>

<style>
.ig-b- { display: inline-block; }
.ig-b- img { visibility: hidden; }
.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
.ig-b-16 { width: 16px; height: 16px; background: url(//badges.instagram.com/static/images/ig-badge-sprite-16.png) no-repeat 0 0; }
.ig-b-16 { background-image: url(//badges.instagram.com/static/images/ig-badge-sprite-16@2x.png); background-size: 60px 178px; } }
</style>

E3DBPI/Views/BlogPosts/Index.cshtml
@model IEnumerable<E3DBPI.Models.BlogPost>

@{
    ViewBag.Title = "Contraxtor News & Events";
}

<div class="listing container">
    <h2>@ViewBag.Title</h2>
    <table class="table" id="articlelist">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Post_Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post_author)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post_Tite)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post_Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post_Featured)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post_Views)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BlogCategory.Post_CategoryName)
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Post_Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Post_author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Post_Tite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Post_Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Post_Featured)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Post_Views)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BlogCategory.Post_CategoryName)
                </td>
                <td width="15%">
                    @Html.ActionLink("View", "Details", new { id = item.PostID }, htmlAttributes: new { @class = "btn btn-xs btn-info" })
                    @Html.ActionLink("Edit", "Edit", new { id = item.PostID }, htmlAttributes: new { @class = "btn btn-xs btn-info" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.PostID }, htmlAttributes: new { @class = "btn btn-xs btn-warning" })
                </td>
            </tr>
        }

    </table>
</div>



<div class="col-md-12">
    <p class="buttonbox">
    <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-lg btn-primary" role="button" aria-disabled="true">Return</a>
    @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("SuperAdmin"))
                {
        @Html.ActionLink("Create a New Article", "Create", "BlogPosts", new { }, htmlAttributes: new { @class = "btn btn-lg btn-primary" })
        }
    }
    </p>

</div>







    <div class="col-md-12" style="text-align:center;margin-top:40px;">
        @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("SuperAdmin"))
                {
            }
        }
    </div>


    @section scripts{
        <script>
            $(document).ready(function () {
                $("#articlelist").DataTable();
            });
        </script>
    }

E3DBPI/Views/BlogPosts/NewsnEvents.cshtml
@model IEnumerable<E3DBPI.Models.BlogPost>

@{
    ViewBag.Title = "Contraxtor™ News & Events";
}

<div class="row mt-5 mb-5">
    <div class="col-md-12">
        <h1 style="text-align:center">@ViewBag.Title</h1>
    </div>
</div>
<div class="card-deck">
    @foreach (var item in Model)
    {
        <div class="card news shadow">
            <a href="Details?ID=@Html.DisplayFor(modelItem => item.PostID)">
            <img class="card-img-top" src="/images/@Html.DisplayFor(modelItem => item.Post_Image1)"></a>
            <h4>@Html.DisplayFor(modelItem => item.Post_Tite)</h4>
            <p style="font-size:1em;color:#000; text-align:center;padding-left:20px;padding-right:20px">@Html.DisplayFor(modelItem => item.Post_Content)</p>
            <p style="font-size:.7em;color:#000; text-align:center;padding-left:20px;padding-right:20px">
                BY: @Html.DisplayFor(modelItem => item.Post_author)
                @Html.DisplayFor(modelItem => item.Post_Date)
            </p>
        </div>
    }
</div>


@*<div class="listing container">
        @foreach (var item in Model)
        {
            <div class="card news shadow">
                <img class="card-img-top" src="/images/@Html.DisplayFor(modelItem => item.Post_Image1)">
                <h4>@Html.DisplayFor(modelItem => item.Post_Tite)</h4>
                <p style="font-size:1em;color:#000; text-align:center;padding-left:20px;padding-right:20px">@Html.DisplayFor(modelItem => item.Post_Content)</p>
                <p style="font-size:.7em;color:#000; text-align:center;padding-left:20px;padding-right:20px">BY: @Html.DisplayFor(modelItem => item.Post_author) 
                @Html.DisplayFor(modelItem => item.Post_Date) 
                @Html.ActionLink("View", "Details", new { id = item.PostID }, htmlAttributes: new { @class = "btn btn-xs btn-info" })</p>
            </div>
        }
</div>*@



<div class="col-md-12">
    <p class="buttonbox">
        <a href="javascript:void(0);" onclick="history.go(-1);" class="btn btn-lg btn-primary" role="button" aria-disabled="true">Return</a>
        @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("SuperAdmin"))
                {
                @Html.ActionLink("Create a New Article", "Create", "BlogPosts", new { }, htmlAttributes: new { @class = "btn btn-lg btn-primary" })
            }
        }
    </p>

</div>







<div class="col-md-12" style="text-align:center;margin-top:40px;">
    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("SuperAdmin"))
        {
        }
    }
</div>


@section scripts{
    <script>
            $(document).ready(function () {
                $("#articlelist").DataTable();
            });
    </script>
}